16-rails-forms/jukebox/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get '/albums', to: 'albums#index', as: 'albums'
  resources :albums, only: [:index, :show, :new, :create], path: '/records'
end

16-rails-forms/jukebox/app/models/album.rb
class Album < ApplicationRecord
end

16-rails-forms/jukebox/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @albums = Album.all
  end

  def new
  end

  def create
    @album = Album.new(album_params)
    @album.save
    redirect_to albums_path
  end

  private
  # require isn't needed unless your params are _nested_
  # If the structure is flat, you should just use permit.
  def album_params
    # params.require(:album).permit(:title, :artist)
    params.permit(:title, :artist, :year, :rating)
  end

end

16-rails-forms/jukebox/app/views/albums/index.html.erb
<h1>Here are all our dope records</h1>

<ul>
  <% @albums.each do |album| %>
    <li><%= link_to(album.title, album_path(album)) %></li>
  <% end %>
</ul>

16-rails-forms/jukebox/app/views/albums/new.html.erb
<h1>Add an Album</h1>

<!-- <form action="<%= albums_path %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
  <input type="text" name="title" placeholder="Title" />
  <input type="text" name="artist" placeholder="Artist" />
  <input type="number" name="year" placeholder="Year" />
  <input type="number" name="rating" placeholder="Rating" />
  <input type="submit" value="Add Album" />
</form> -->

<%= form_tag(albums_path) do %>
  <%= text_field_tag("title", nil, placeholder: "Title") %>
  <%= text_field_tag("artist", nil, placeholder: "Artist") %>
  <%= number_field_tag("year", nil, placeholder: "Year", in: 1900..2020) %>
  <%= number_field_tag("rating", nil, placeholder: "Rating", in: 1..10) %>
  <%= submit_tag("Add Album") %>
<% end %>

<%= link_to("Homepage", albums_path) %>

16-rails-forms/jukebox/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsForms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>