17-rails-associations-validations/cute_rates/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'example#testing'

  resources :pets, except: [:destroy]
  resources :people, only: [:show, :index, :new, :create]
end

17-rails-associations-validations/cute_rates/app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
    render :index
  end

  def show
    @pet = Pet.find(params[:id])
    render :show
  end

  def new
    @pet = Pet.new
    @people = Person.all
    render :new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet.id)
    else
      render :new
    end
  end

  def edit
    @pet = Pet.find(params[:id])
    render :edit
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update(pet_params)
    redirect_to pet_path(@pet.id)
  end

  private
  def pet_params
    params.require(:pet).permit(:name, :image, :likes, :person_id)
  end
end

17-rails-associations-validations/cute_rates/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CuteRates</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

17-rails-associations-validations/cute_rates/app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name %>
  <%= f.label "Image" %>
  <%= f.text_field :image %>
  <%= f.label "Likes" %>
  <%= f.number_field :likes %>
  <%= f.label "Owner" %>
  <%= f.collection_select(:person_id, @people, :id, :name) %>
  <%= f.submit %>
<% end %>

17-rails-associations-validations/cute_rates/app/views/pets/show.html.erb
<h1>What a cute pet!</h1>
<h2><%= @pet.name %></h2>
<h3>Owner: <%= link_to(@pet.person.name, person_path(@pet.person)) %></h3>
<h4>Likes: <%= @pet.likes %></h4>

<img style="width: 50%; height: 50%;" src="<%= @pet.image %>" />

<%= link_to("All Pets", pets_path) %>